# Generated by Django 4.2.30 on 2026-07-03 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_floor_plan', '0010_add_floorplantile_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='background_image',
            field=models.ImageField(blank=True, height_field='background_image_height', null=True, upload_to='floor_plan_backgrounds/', width_field='background_image_width'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='background_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='background_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='background_opacity',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='bg_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='bg_rotation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='bg_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='bg_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='bg_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='placement_mode',
            field=models.CharField(default='grid', max_length=10),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='show_grid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='floorplantile',
            name='height',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='floorplantile',
            name='pos_x',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='floorplantile',
            name='pos_y',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='floorplantile',
            name='rotation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='floorplantile',
            name='width',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
