# Generated by Django 4.2.30 on 2026-07-03 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_floor_plan', '0011_add_background_and_freeform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplantile',
            name='pos_x',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='floorplantile',
            name='pos_y',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='floorplantile',
            name='x_origin',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='floorplantile',
            name='y_origin',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='floorplantile',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('x_origin__isnull', False), ('y_origin__isnull', False)), models.Q(('x_origin__isnull', True), ('y_origin__isnull', True)), _connector='OR'), name='floorplantile_origin_pairing'),
        ),
    ]
