# Generated by Django 4.2.30 on 2026-07-03 02:39

import django.db.models.deletion
from django.db import migrations, models

# Legacy typed FK -> (dcim app_label, model_name) for backfilling the generic placement pair.
_TYPED_SPECS = (
    ("rack", "dcim", "rack"),
    ("device", "dcim", "device"),
    ("power_panel", "dcim", "powerpanel"),
    ("power_feed", "dcim", "powerfeed"),
)


def backfill_generic_from_typed(apps, schema_editor):
    """Mirror each tile's populated typed FK into the generic placement pair + label.

    Reads raw ``<field>_id`` columns and object ``name`` values (never dereferences a FK through the
    frozen historical model, and never calls str(obj)), so it is safe and cheap.
    """
    Tile = apps.get_model("nautobot_floor_plan", "FloorPlanTile")
    ContentType = apps.get_model("contenttypes", "ContentType")

    ct_by_field = {}
    names_by_field = {}
    for field, app_label, model_name in _TYPED_SPECS:
        try:
            ct_by_field[field] = ContentType.objects.get(app_label=app_label, model=model_name)
            model = apps.get_model(app_label, model_name)
            names_by_field[field] = dict(model.objects.values_list("pk", "name"))
        except Exception:  # noqa: BLE001  target app/model unavailable; skip that type
            ct_by_field[field] = None
            names_by_field[field] = {}

    updates = []
    for tile in Tile.objects.filter(placed_object_id__isnull=True):
        for field, _app_label, _model_name in _TYPED_SPECS:
            obj_id = getattr(tile, f"{field}_id")
            if obj_id and ct_by_field[field] is not None:
                tile.placed_content_type_id = ct_by_field[field].pk
                tile.placed_object_id = obj_id
                tile.placed_label = (names_by_field[field].get(obj_id) or "")[:255]
                updates.append(tile)
                break
    if updates:
        Tile.objects.bulk_update(updates, ["placed_content_type", "placed_object_id", "placed_label"], batch_size=500)


def clear_generic_placement(apps, schema_editor):
    """Reverse: clear the generic pair + label. Typed FKs are untouched, so no data is lost."""
    Tile = apps.get_model("nautobot_floor_plan", "FloorPlanTile")
    Tile.objects.update(placed_content_type=None, placed_object_id=None, placed_label="")


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("nautobot_floor_plan", "0012_freeform_validation_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="floorplantile",
            name="placed_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="floor_plan_tiles",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="floorplantile",
            name="placed_label",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name="floorplantile",
            name="placed_object_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_generic_from_typed, clear_generic_placement),
        migrations.AddConstraint(
            model_name="floorplantile",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("placed_content_type__isnull", False), ("placed_object_id__isnull", False)),
                    models.Q(("placed_content_type__isnull", True), ("placed_object_id__isnull", True)),
                    _connector="OR",
                ),
                name="floorplantile_placed_object_pairing",
            ),
        ),
        migrations.AddConstraint(
            model_name="floorplantile",
            constraint=models.UniqueConstraint(
                fields=("placed_content_type", "placed_object_id"), name="floorplantile_unique_placed_object"
            ),
        ),
    ]
