# Generated by Django 4.2.30 on 2026-07-04 01:51

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0132_approval_workflow_seed_data'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('nautobot_floor_plan', '0013_add_generic_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlanObjectType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('variant_key', models.CharField(blank=True, max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=6)),
                ('glyph_key', models.CharField(blank=True, max_length=50)),
                ('custom_glyph_paths', models.JSONField(blank=True, null=True)),
                ('glyph_viewbox', models.PositiveSmallIntegerField(default=24)),
                ('legend_order', models.IntegerField(default=100)),
                ('location_field', models.CharField(default='location', max_length=100)),
                ('match_field', models.CharField(blank=True, max_length=100)),
                ('match_keywords', models.JSONField(blank=True, null=True)),
                ('match_precedence', models.IntegerField(default=100)),
                ('override', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan_object_types', to='contenttypes.contenttype')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['content_type', 'legend_order', 'label'],
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='floorplanobjecttype',
            constraint=models.UniqueConstraint(fields=('content_type', 'variant_key'), name='floorplanobjecttype_unique_type_variant'),
        ),
    ]
