# Generated by Django 4.2.30 on 2026-07-08 20:56

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0132_approval_workflow_seed_data'),
        ('nautobot_floor_plan', '0014_add_floorplanobjecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='source_document',
            field=models.FileField(blank=True, null=True, upload_to='floor_plan_sources/'),
        ),
        migrations.CreateModel(
            name='BlueprintPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('page_number', models.PositiveIntegerField()),
                ('image', models.ImageField(height_field='image_height', upload_to='floor_plan_pages/', width_field='image_width')),
                ('image_width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='floor_plan_page_thumbs/')),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprint_pages', to='nautobot_floor_plan.floorplan')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['floor_plan', 'page_number'],
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='blueprintpage',
            constraint=models.UniqueConstraint(fields=('floor_plan', 'page_number'), name='blueprintpage_unique_plan_page'),
        ),
    ]
