# Generated by Django 4.2.30 on 2026-07-10 21:56

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0132_approval_workflow_seed_data'),
        ('nautobot_floor_plan', '0015_add_blueprint_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlanLayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=6)),
                ('opacity', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('default_visible', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=100)),
                ('floor_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='nautobot_floor_plan.floorplan')),
                ('source_content_types', models.ManyToManyField(blank=True, related_name='floor_plan_layers', to='contenttypes.contenttype')),
                ('source_dynamic_groups', models.ManyToManyField(blank=True, related_name='floor_plan_layers', to='extras.dynamicgroup')),
                ('source_tags', models.ManyToManyField(blank=True, related_name='floor_plan_layers', to='extras.tag')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FloorPlanLayerObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('object_id', models.UUIDField(db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan_layer_objects', to='contenttypes.contenttype')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_objects', to='nautobot_floor_plan.floorplanlayer')),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['layer'],
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='floorplanlayerobject',
            constraint=models.UniqueConstraint(fields=('layer', 'content_type', 'object_id'), name='floorplanlayerobject_unique_member'),
        ),
        migrations.AddConstraint(
            model_name='floorplanlayer',
            constraint=models.UniqueConstraint(fields=('floor_plan', 'name'), name='floorplanlayer_unique_plan_name'),
        ),
    ]
