# Generated by Django 4.2.30 on 2026-07-10 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_floor_plan', '0016_add_floorplanlayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='icon_scale',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.AddField(
            model_name='floorplantile',
            name='icon_scale',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
